# ndarray :N-Dimensional Array

In [2]:
import numpy as np

- numpy는 np.array 함수를 활용하여 배열을 생성함 -> ndarray <br>
- numpy는 하나의 데이터 type만 배열에 넣을 수 있음<br/>
- Dynamic typing not supported

In [3]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array.dtype # Array 전체의 데이터 type

dtype('float64')

In [6]:
test_array = np.array([1,4,5,"8"], float)
print(test_array)
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


## Array Shape (matrix)
- returns tuple

### Matrix

In [7]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

### 3rd Order Tensor

In [8]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], [[1,2,5,8],[1,2,5,8],[1,2,5,8]], [[1,2,5,8],[1,2,5,8],[1,2,5,8]], [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

## Array ndim & size
- ndim : the number of dimension <br/>
- size : the number of data

In [9]:
np.array(tensor, int).ndim

3

In [10]:
np.array(tensor, int).size

48

## Array dtype
- Ndarray의 single element가 가지는 data type<br/>
- 각 element가 차지하는 memory의 크기가 결정됨

In [11]:
np.array([[1,2,3], [4.5, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

- Compatible with data types of C

<img src="./img/ndarray_dtype.png" width="800" style="float: left">

- nbytes : returns the memory size of ndarray object

In [14]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float32).nbytes # 32bits = 4bytes

24

In [15]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.int8).nbytes # 8bits = 1bytes

6

In [16]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float64).nbytes

48

# Shape Handling

## reshape
- np.array(`array`).reshape(`shape`)  
- Resize the shape of array (the number of elements stays the same)

In [17]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(8,).shape

(8,)

- Array의 size만 같다면 다차원으로 자유로이 변형가능

In [20]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [22]:
# -1 : size를 기반으로 row 개수 선정
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [23]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [24]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [25]:
np.array(test_matrix).reshape(1,1,-1,2)

array([[[[1, 2],
         [3, 4],
         [1, 2],
         [5, 8]]]])

## flatten
- flatten()  
- 다차원 array를 1차원 array로 변환

In [27]:
test_matrix = [[1,2,3,4], [1,2,5,8],[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# Indexing & Slicing

## Indexing
- List와 달리 이차원 배열에서 [0,0] 과 같은 표기법을 제공함  
- Matrix일 경우 앞은 row 뒤는 column을 의미함

In [28]:
a = np.array([[1,2,3], [4.5, 5, 6]], int)
print(a)
print(a[0,0]) # Two dimensional array representation 1
print(a[0][0]) # Two dimensional array representation 2

[[1 2 3]
 [4 5 6]]
1
1


In [29]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [30]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [31]:
test_example = np.array([[1,2,3], [4.5, 5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
test_example[0][0]

1

In [33]:
test_example[0,0]

1

In [34]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [35]:
test_example[0][0] = 5
test_example[0,0]

5

## Slicing
- List와 달리 row와 column부분을 나눠서 slicing이 가능함  
- Matrix의 부분 집합을 추출할 때 유용함

In [41]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
a[:,2:] # 전체 Row의 Col2 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [40]:
a[1,1:3] # Row1의 Col1~Col2

array([7, 8])

In [42]:
a[1:3] # Row1 ~ Row2 전체

array([[ 6,  7,  8,  9, 10]])

In [44]:
test_example = np.array([
    [1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]
], int)

test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [45]:
test_example[:2,:] # 두번째 Row까지 전체 Col

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [46]:
test_example[:,1:3] #전체 Row, Col1~Col2

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [48]:
test_example[1,:2] # Row1, 두번째 Col까지

array([1, 2])

In [49]:
test_example = np.array([[1,2,3,4,5], [6,7,8,9,10]])
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
test_example[:, 2:] #전체 Row, Col2부터 전체

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [51]:
test_example[1,1:3] # Row1, Col1부터 세번째 Col까지

array([7, 8])

In [52]:
test_example[1:3] # Row1 ~ Row2 전체

array([[ 6,  7,  8,  9, 10]])

In [54]:
test_a = np.array([[0,1,2,3,4,], [5,6,7,8,9], [10,11,12,13,14]])
test_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
test_a[:,::2] #전체 Row, 전체 Col, 한칸씩 건너뛰어서

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [56]:
test_a[::2,::3] #전체 Row 한칸씩 건너뛰어서, 전체 Col 두칸씩 건너뛰어서

array([[ 0,  3],
       [10, 13]])

More Reference : https://www.slideshare.net/PyData/introduction-to-numpy


# Creation Functions

## arange
- array의 범위를 지정하여 값의 list를 생성  
- np.arange(`start`, `end`, `step`)

In [57]:
np.arange(30) # range: list의 range와 같은 효과로, int 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
np.arange(0, 5, 0.5) # 0부터, 5까지, 0.5씩 건너뛰어서

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [59]:
np.arange(30).reshape(5,6) #arange x reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
np.arange(0, 5, 0.5).tolist() # array to list

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

## zeros
- 0으로만 구성된 ndarray 생성  
- np.zeros(`shape`, `dtype`, `order`)

In [63]:
np.zeros(shape=(10,), dtype=np.int8) # 10개의 0으로 된 vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [65]:
np.zeros((2,5)) # 2 by 5 - zero matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones
- 1로만 구성된 ndarray 생성  
- np.ones(`shape`, `dtype`, `order`)

In [66]:
np.ones(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [67]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## empty
- shape만 주어지고 비어있는 ndarray 생성(memory initialization이 되지 않음)  
- np.empty(`shape`, `dtype`)

In [69]:
np.empty(shape=(10,), dtype=np.int8)

array([ 96,  56,  49, -25,  83,   2,   0,   0,   0,   0], dtype=int8)

In [70]:
np.empty((3,5))

array([[4.67296746e-307, 1.69121096e-306, 7.56593696e-307,
        8.34441742e-308, 1.78022342e-306],
       [6.23058028e-307, 9.79107872e-307, 6.89807188e-307,
        7.56594375e-307, 6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        2.04712907e-306, 3.49698923e-317]])

## \_like
- 기존 ndarray의 shape만큼 1,0 또는 empty array를 반환  
- np.`zeros, ones, empty`\_like(`array`)

In [71]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity
- Identity Matrix 생성
- np.identity(`number of rows`, `dtype`)

In [72]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [73]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## eye
- 대각선이 1인 matrix 만들어줌  
- starting index인 k값 변경 가능  
- np.eye(`row`, `col`, `k(start index)`)

In [75]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag
- 대각 행렬의 값을 추출함
- np.diag(`matrix`, `start index, k`)

In [78]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [79]:
np.diag(matrix, k=1)

array([1, 5])

## random sampling
- 데이터 분포에 따른 sampling으로 array를 생성  
- reshape과 많이 씀
- np.random.uniform(`min`, `max`, `number of element`) : 균등분포  
- np.random.normal(`average`,`standard deviation`,`number of element`): 정규분포

In [80]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.94463232, 0.56957733, 0.6727776 , 0.60233676, 0.39475849],
       [0.68944997, 0.45733711, 0.91525769, 0.90492253, 0.03740618]])

In [81]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.1455509 , -0.79858162,  0.92407381, -0.80396203,  0.38633144],
       [ 1.22470259, -0.30165471,  1.1206826 , -1.09658798, -0.41468752]])

# Operation Functions

## Important Concept : axis

<img src="./img/np_axis.png" width="700" style="float:left">

## sum
- ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

In [83]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
test_array.sum(dtype=np.float)

55.0

In [85]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
test_array.sum(axis=0) # axis=0로 sum

array([15, 18, 21, 24])

In [86]:
test_array.sum(axis=1) # axis=1로 sum

array([10, 26, 42])

In [89]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [90]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [91]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [92]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

## mean & std
- ndarray의 element간의 평균 또는 표준편차를 반환

In [93]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
test_array.mean()

6.5

In [95]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [96]:
test_array.std()

3.452052529534663

In [97]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

## Mathematical Functions

- exponential : exp, expm1, exp2, log, log10, log1p, log2, power, sqrt  
- trigonometric : sin, cos, tan, acsin, arcos, atctan  
- hyperbolic: sinh, cosh, tanh, acsinh, arccosh, atctanh

In [98]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [99]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

## Concatenate : vstack, hstack, concatenate
- Numpy array를 합치는 함수

In [100]:
# vstack 
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [101]:
# hstack 1 column vector
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [104]:
# hstack 2 column vector
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.hstack((a,b))

array([[1, 2, 3, 2, 3, 4]])

In [105]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 2, 3, 4])

In [106]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1) # transpose

array([[1, 2, 5],
       [3, 4, 6]])

# Array Operations