# The Concepts of a Feature

## Feature
- An individual measurable property or characteristic of a phenomenon being observed<br/>
- same as independent variable and input<br/>
- Usually a column in a table<br/>
- A data instance can be expressed as a feature vector
- A **feature vector** is an n-dimensional vector of numerical features that represent some object.

# Data Types

- continuous / discrete <br/>
continuous : Usually real values ex) temperature, grade average, velocity <br/>
discrete : Usually labled values ex) sex, zip code, rank

- Numeric Types <br/>
mesurable data type<br/>
integer / real-number<br/>
ex ) temperature, velocity, year or day<br/>
Interval-scaled type, ratio-scaled type

- Nomial Types<br/>
can be categorized <br/>
ex) color, ID, school name, major<br/>
two categories => binary type

- Ordinal Types<br/>
can be categorized but categories have an order<br/>
ex) gpa, size of a bottle<br/>
measured scale or unit may differ<br/>
Having an order does not implies multiplication

# Loading Data with Pandas

<img src="./img/ml_data_def.png" width="600" style="float : left">

In [1]:
# import pandas library
import pandas as pd

In [2]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None) #load csv data, empty separate, no column

In [3]:
df_data.head(10)

0     1     2   3      4      5      6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575   65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421   78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185   61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998   45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147   54.2  6.0622   3  222.0  18.7   
5  0.02985   0.0  2.18   0  0.458  6.430   58.7  6.0622   3  222.0  18.7   
6  0.08829  12.5  7.87   0  0.524  6.012   66.6  5.5605   5  311.0  15.2   
7  0.14455  12.5  7.87   0  0.524  6.172   96.1  5.9505   5  311.0  15.2   
8  0.21124  12.5  7.87   0  0.524  5.631  100.0  6.0821   5  311.0  15.2   
9  0.17004  12.5  7.87   0  0.524  6.004   85.9  6.5921   5  311.0  15.2   

       11     12    13  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  
5  394.12   5.21  28.7  
6  395.60  12.43  22.9  
7  396.90  19.15  27.1  
8  386.63  29.93  16.5  
9  386.71  17.10  18.9

In [4]:
# assign column names as a list
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRARIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRARIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

# Representing a Model with Numpy

<img src="./img/ml_numpy_eq.png" width="600" style="float: left">

In [5]:
# import numpy lib
import numpy as np

In [8]:
# make two dimensional vectors
weight_vector = np.array([[1], [1], [1]]) 
x_vector = np.array([[3], [4], [5]])

In [10]:
# transpose of weight vector
weight_vector.T

array([[1, 1, 1]])

In [9]:
# dot product of transpose of weight vector and x vector
weight_vector.T.dot(x_vector)

array([[12]])

## Equation Format
<img src="./img/ml_pn_eq.png" width="600" style="float: left">

## Another Example

In [11]:
# import pandas as pd already done above
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRARIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [12]:
# add w0's col and insert 1 to them
df_data['weight_0'] = 1

# remove MEDV col since it stands for Y, not X
df_data = df_data.drop('MEDV', axis = 1)

df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRARIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [13]:
df_data.as_matrix()

c:\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [14]:
# get the dimension of data
df_data.shape

(506, 14)

In [15]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14, 1))

c:\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [17]:
weight_vector

array([[0.35043066],
       [0.45217015],
       [0.65880949],
       [0.52036076],
       [0.73660951],
       [0.09401056],
       [0.17914134],
       [0.8268971 ],
       [0.53968704],
       [0.52160813],
       [0.32140644],
       [0.07261295],
       [0.29997375],
       [0.17845014]])

In [16]:
df_matrix.dot(weight_vector)

array([[216.08517797],
       [188.62786298],
       [183.6825636 ],
       [168.8022773 ],
       [171.21569459],
       [171.70282733],
       [230.78459442],
       [238.5367312 ],
       [241.80469467],
       [235.87829328],
       [238.66124035],
       [234.61179544],
       [226.35361393],
       [222.02080612],
       [225.27516267],
       [220.85702639],
       [214.93958375],
       [226.45773115],
       [209.96064771],
       [223.1335499 ],
       [230.30528343],
       [227.78735311],
       [230.14007873],
       [231.78492821],
       [229.81752013],
       [221.82104713],
       [227.61835055],
       [222.90380398],
       [228.46456502],
       [226.3057132 ],
       [229.2026556 ],
       [228.65856553],
       [219.21614586],
       [227.62490489],
       [220.71745584],
       [206.1707687 ],
       [204.08479102],
       [201.58706853],
       [199.691076  ],
       [214.32088032],
       [212.58578666],
       [169.3366007 ],
       [170.09069449],
       [171

# Linear Algebra Concepts

## Vector

<img src="./img/linear_algebra_1.png" width="400" style="float: left">

<img src="./img/scalar_product.png" width="400" style="float:left">

## Matrix

<img src="./img/matrix_type.png" width="400" style="float:left">

### Equality of Matrices
If aij is an element of matrix A and bij is element of matrix B, then the matrix A and B are equal only if a = b for all i and j values. Two matrices to be equal, their order must be the same. If two matrices have their corresponding elements equal, then they are called equal matrices.

<img src="./img/scalar_matrix.png" width="400" style="float:left">

<img src="./img/transpose.png" width="500" style="float:left">

<img src="./img/transpose_prop.png" width=700 style="float:left">

### Matrix Multiplication

<img src="./img/matrix_mult.png" width="500" style="float:left">

# Linear Algebra with Python

## Vector Representation of Python

In [2]:
vector_a = [1, 2, 10] # list 
vector_b = (1, 2, 10) # tuple
vector_c = {'x':1, 'y':2, 'z':10} #dict

print(vector_a, vector_b, vector_c) #anything is possible

[1, 2, 10] (1, 2, 10) {'x': 1, 'y': 2, 'z': 10}


In [3]:
# vector addition
u = [2, 2]
v = [2, 3]
z = [3, 5]

result = [sum(t) for t in zip(u,v,z)]
result

[7, 10]

In [4]:
# scalar-vector product
u = [1, 2, 3]
v = [4, 4, 4]
alpha = 2

result = [alpha*sum(t) for t in zip(u,v)]
result

[10, 12, 14]

## Matrix Representation of Python

In [5]:
matrix_a = [[3,6], [4,5]] # list 
matrix_b = [(3,6), (4,5)] # tuple
matrix_c = {(0,0):3, (0,1):6, (1,0):4, (1,1):5} #dict

In [6]:
# matrix addition: 
# zip rows first and then zip elements
matrix_a = [[3,6], [4,5]]
matrix_b = [[5,8], [6,7]]
result = [[sum(row) for row in zip(*t)] for t in zip(matrix_a, matrix_b)]

result

[[8, 14], [10, 12]]

In [11]:
# scalar-matrix product
matrix_a = [[3,6], [4,5]]
alpha = 4
result = [[alpha * element for element in t] for t in matrix_a]

result

[[12, 24], [16, 20]]

In [13]:
# matrix transpose
matrix_a = [[1,2,3], [4,5,6]]
result = [[element for element in t] for t in zip(*matrix_a)]
# [t for t in zip(*matrix_a)] -> [(1,4), (2,5), (3,6)]
result

[[1, 4], [2, 5], [3, 6]]

In [17]:
# matrix product
matrix_a = [[1,1,2], [2,1,1]]
matrix_b = [[1,1], [2,1], [1,3]]
result = [[sum(a*b for a,b in zip(row_a, column_b)) 
           for column_b in zip(*matrix_b)] for row_a in matrix_a]

result

[[5, 8], [5, 6]]

In [19]:
#row단위로 뺄때 zip(matrix)
[row_a for row_a in matrix_a]

[[1, 1, 2], [2, 1, 1]]

In [21]:
#column단위로 뺄때 zip(*matrix)
[column_b for column_b in zip(*matrix_b)]

[(1, 2, 1), (1, 1, 3)]

In [26]:
row_a = [row_a for row_a in matrix_a]
column_b = [column_b for column_b in zip(*matrix_b)]
for a,b in zip(row_a, column_b):
    print(a,b)

[1, 1, 2] (1, 2, 1)
[2, 1, 1] (1, 1, 3)


## for n vectors

In [36]:
def vector_addition(*args):
    return [sum(t) for t in zip(*args)]

In [37]:
vector_addition([1,2],[2,3],[3,4])

[6, 9]